server:
  verbosity: 1
  interface: 0.0.0.0
  port: 53
  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes
  access-control: 0.0.0.0/0 allow
  harden-glue: yes
  harden-dnssec-stripped: yes
  chroot: ""
  logfile: ""
  use-syslog: no
