server:
  verbosity: 1
  interface: 0.0.0.0
  port: 53

  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes

  harden-glue: yes
  harden-dnssec-stripped: yes
  harden-large-queries: yes
  harden-short-bufsize: yes
  harden-algo-downgrade: yes

  prefetch: yes
  prefetch-key: yes
  qname-minimisation: yes
  qname-minimisation-strict: no

  cache-max-ttl: 86400
  cache-min-ttl: 300
  infra-cache-numhosts: 10000

  auto-trust-anchor-file: "/var/lib/unbound/root.key"
  val-log-level: 1

  rrset-roundrobin: yes
  minimal-responses: yes

  outgoing-num-tcp: 10
  incoming-num-tcp: 10
  num-threads: 2

  private-address: 192.168.0.0/16
  private-address: 172.16.0.0/12
  private-address: 10.0.0.0/8
  private-address: 127.0.0.0/8

  do-not-query-localhost: no

  statistics-interval: 0
  extended-statistics: yes

forward-zone:
  name: "."
  forward-tls-upstream: yes
  forward-addr: 9.9.9.9@853#dns.quad9.net
  forward-addr: 149.112.112.112@853#dns.quad9.net
  forward-addr: 1.1.1.1@853#cloudflare-dns.com
  forward-addr: 1.0.0.1@853#cloudflare-dns.com
